# This workflow will verify that all PRs have at
# least one of the [scope] labels before they can be merged.

name: Verify PR labels
on:
  pull_request_target:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  check_pr_label:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    name: Verify that the PR has a valid label
    steps:
    - name: Verify PR label action
      uses: jesusvasquez333/verify-pr-label-action@v1.4.0
      id: verify-pr-label
      with:
        github-token: ${{ github.TOKEN }}
        valid-labels: '[scope] bug, [scope] enhancement, [scope] documentation, [scope] significant, [scope] maintenance'
        pull-request-number: ${{ github.event.pull_request.number }}
        disable-reviews: false
